[project-init]
command=mkdir build && cmake -DCMAKE_CXX_COMPILER=clang++ -S . -B build -G "Ninja"
cwd=$(VIM_ROOT)
output=terminal
pos=floaterm_build
errorformat=

[project-build]
command=cmake --build build --target all -j 18
cwd=<root>
output=terminal
pos=floaterm_build
errorformat=%f:%l:%m

[project-run]
command=make run
# <root> is an alias to `$(VIM_ROOT)`, a little easier to type.
cwd=<root>
output=terminal
pos=floaterm_run
