require('keymaps.which_key.wk_a_dap')
require('keymaps.which_key.wk_b_tabs')
require('keymaps.which_key.wk_e_tabedit')
require('keymaps.which_key.wk_l_lsp')
require('keymaps.which_key.wk_s_sessions')
require('keymaps.which_key.wk_semicolon_toggleterm')
require('keymaps.which_key.wk_single_key')
require('keymaps.which_key.wk_t_telescope')
require('keymaps.which_key.wk_T_trouble')
require('keymaps.which_key.wk_w_windows')
-- require('keymaps.which_key.wk_w_tabs')
require('keymaps.which_key.wk_z_lazynvim')
